export let blogPosts = [
    [
        [
            "De afgelopen week stond in het teken van kennismaking met nieuwe projecten en technologieën. In het begin van de week werden de projecten verdeeld en kregen we een rondleiding met uitleg over de gebruikte technologieën en de verwachtingen binnen het project.",
            "Daarna installeerde ik Angular CLI en Node.js en ging ik aan de slag met een opdracht die uit meerdere delen bestond. Het eerste deel kon ik grotendeels afronden, al bleef de loading state nog een uitdaging. In de daaropvolgende dagen werkte ik de opdracht volledig af en leerde ik werken met Bootstrap en PrimeNG om een gebruiksvriendelijke interface te bouwen.",
            "Verder verdiepte ik me in SQL door queries uit verschillende C#-functies te halen, onder andere voor gebruikers, groupflows en massainschrijving. Dit gaf me een beter inzicht in de samenwerking tussen de applicatie en de database. Een vergadering zorgde daarnaast voor extra duidelijkheid over het project en de verdere aanpak.",
            "Aan het einde van de week werden de SQL-queries afgerond en diende ik een document in om binnenkort mijn badge te kunnen behalen. Tot slot begon ik met het bouwen van deze blog in Angular, zodat ik de technologie beter leer begrijpen door ze in de praktijk toe te passen."
        ]
    ],
    [
        [
            "Deze week stond volledig in het teken van bijleren, doorzetten en stap voor stap vooruitgang boeken. Zowel backend als frontend kwamen aan bod, met de nodige uitdagingen én waardevolle leermomenten.",
            "Ik begon de week met verder te werken aan mijn blogproject om mijn kennis van Angular uit te breiden. Door actief te bouwen merk ik dat ik de structuur en werking van Angular steeds beter begrijp. Daarnaast hebben we ook het nieuwe EF Core-document doorgenomen, omdat er nog enkele zaken ontbraken.",
            "Vanaf dinsdag ben ik gestart met de EF Core - oefening.In het begin liep ik tegen een technisch probleem aan: de connectie tussen Visual Studio en SQL Server werkte niet zoals het hoorde.Met de hulp van Rabin kreeg ik dit gelukkig opgelost.Daarna volgde nog een tweede uitdaging met een stuk code dat ik had overgenomen uit het EF Core - document.Het werkte niet correct, en het was niet meteen duidelijk waarom.",
            "Woensdag heb ik samen met Kevin het probleem verder bekeken via een call.Uiteindelijk bleek dat ik bij het overnemen van de code een onderdeel niet had aangepast.Een kleine fout, maar met grote gevolgen.Het was een goede les: code overnemen zonder volledig te begrijpen wat elk onderdeel doet, kan snel voor problemen zorgen.De rest van de dag heb ik intensief verder gewerkt aan de oefening, waardoor ik mooie vooruitgang kon boeken.Bovendien kreeg ik toegang tot de frontendcode in GitLab, wat betekende dat ik ook daar binnenkort kon starten.",
            "Donderdag stond in het teken van verdieping.Ik heb bewust tijd genomen om EF Core beter te begrijpen: hoe dbContext werkt, hoe relaties werken en wat er precies gebeurt bij database - interacties.Door niet enkel te focussen op “het werkend krijgen”, maar ook op het begrijpen van de achterliggende werking, voel ik dat mijn kennis sterker wordt.",
            "Vrijdag ben ik gestart met de frontend in Angular en heb ik gewerkt aan de inschrijvingenpagina.Het grootste deel daarvan is ondertussen afgewerkt.Er blijven nog twee functies over die ik volgende week zal implementeren, maar de basis staat er en alles begint mooi samen te komen.",
            "Terugkijkend was dit een week waarin ik niet alleen technische vooruitgang heb geboekt, maar ook heb geleerd hoe belangrijk nauwkeurigheid, samenwerking en dieper begrip zijn binnen development.Kleine fouten kunnen veel tijd kosten, maar leveren uiteindelijk ook waardevolle inzichten op.Op naar volgende week, waar ik de laatste functionaliteiten verder zal uitwerken en alles verder zal verfijnen."

        ]
    ],
    [
        [
            "Deze week stond in het teken van structuur opzetten, efficiënter leren werken en omgaan met de minder zichtbare — maar minstens even belangrijke — kant van development.",
            "Maandag kreeg ik toegang tot het Jira - board, wat meteen zorgde voor meer overzicht in de taken en planning.Daarnaast hebben we een database opgezet in een Docker - container.We leerden ook hoe we binnen dit project een nieuwe pagina aan het navigatiemenu moeten toevoegen, wat handig is voor extra pagina’s aan te maken.Een belangrijke ontdekking was dat ik met PrimeNG veel minder TypeScript - code hoef te schrijven.Als ik dat eerder had beseft, had me dat al heel wat tijd kunnen besparen.",
            "Dinsdag heb ik mijn eerdere TypeScript - functionaliteiten grotendeels vervangen door PrimeNG - oplossingen.Dat zorgde niet alleen voor kortere code, maar ook voor een nettere en efficiëntere implementatie.Vervolgens heb ik alle nodige data in de database geplaatst zodat alles correct getest kon worden.Daarna ben ik begonnen met het mobiel maken van de enrollments - pagina.Dat was een taak die meer aandacht vroeg dan verwacht.",
            "Woensdag heb ik eerst het design van de knoppen op de enrollments - pagina aangepast.Daarna heb ik de volledige pagina responsive gemaakt.Dat proces nam behoorlijk wat tijd in beslag, vooral omdat elk detail correct moest schalen en werken op verschillende schermgroottes.In de namiddag hadden we een vergadering, waarna ik gestart ben met de flows - pagina.De eerste sectie daarvan heb ik meteen afgewerkt én responsive gemaakt.",
            "Donderdag werkte ik ’s ochtends de CSS van de flows - pagina verder af.Daarna begon ik aan de TypeScript - en PrimeNG - functionaliteiten.Tegen de namiddag had ik alles geïmplementeerd, al liep ik even vast op een specifieke functionaliteit omdat ik de vereisten verkeerd had begrepen.Na wat herbekijken en aanpassen is het uiteindelijk toch gelukt.Vervolgens probeerde ik mijn branch te rebasen om een merge request aan te maken, maar ik kreeg te maken met stevige merge - conflicten.Dat zorgde voor een onverwachte uitdaging.",
            "Vrijdag stond grotendeels in het teken van het oplossen van die rebase - problemen.Het kostte behoorlijk wat tijd om alles correct samen te voegen zodat ik mijn merge request kon voorbereiden.Daarnaast heb ik scripts gerund en de connection string aangepast om de API correct werkend te krijgen.Tot slot heb ik nog extra informatie opgezocht over EF Core om mijn begrip verder te verdiepen."

        ]
    ]
]