export let blogPosts = [
    [
        [
            "De afgelopen week stond in het teken van kennismaking met nieuwe projecten en technologieën. In het begin van de week werden de projecten verdeeld en kregen we een rondleiding met uitleg over de gebruikte technologieën en de verwachtingen binnen het project.",
            "Daarna installeerde ik Angular CLI en Node.js en ging ik aan de slag met een opdracht die uit meerdere delen bestond. Het eerste deel kon ik grotendeels afronden, al bleef de loading state nog een uitdaging. In de daaropvolgende dagen werkte ik de opdracht volledig af en leerde ik werken met Bootstrap en PrimeNG om een gebruiksvriendelijke interface te bouwen.",
            "Verder verdiepte ik me in SQL door queries uit verschillende C#-functies te halen, onder andere voor gebruikers, groupflows en massainschrijving. Dit gaf me een beter inzicht in de samenwerking tussen de applicatie en de database. Een vergadering zorgde daarnaast voor extra duidelijkheid over het project en de verdere aanpak.",
            "Aan het einde van de week werden de SQL-queries afgerond en diende ik een document in om binnenkort mijn badge te kunnen behalen. Tot slot begon ik met het bouwen van deze blog in Angular, zodat ik de technologie beter leer begrijpen door ze in de praktijk toe te passen."
        ]
    ],
    [
        [
            "Deze week stond volledig in het teken van bijleren, doorzetten en stap voor stap vooruitgang boeken. Zowel backend als frontend kwamen aan bod, met de nodige uitdagingen én waardevolle leermomenten.",
            "Ik begon de week met verder te werken aan mijn blogproject om mijn kennis van Angular uit te breiden. Door actief te bouwen merk ik dat ik de structuur en werking van Angular steeds beter begrijp. Daarnaast hebben we ook het nieuwe EF Core-document doorgenomen, omdat er nog enkele zaken ontbraken.",
            "Vanaf dinsdag ben ik gestart met de EF Core - oefening.In het begin liep ik tegen een technisch probleem aan: de connectie tussen Visual Studio en SQL Server werkte niet zoals het hoorde.Met de hulp van Rabin kreeg ik dit gelukkig opgelost.Daarna volgde nog een tweede uitdaging met een stuk code dat ik had overgenomen uit het EF Core - document.Het werkte niet correct, en het was niet meteen duidelijk waarom.",
            "Woensdag heb ik samen met Kevin het probleem verder bekeken via een call.Uiteindelijk bleek dat ik bij het overnemen van de code een onderdeel niet had aangepast.Een kleine fout, maar met grote gevolgen.Het was een goede les: code overnemen zonder volledig te begrijpen wat elk onderdeel doet, kan snel voor problemen zorgen.De rest van de dag heb ik intensief verder gewerkt aan de oefening, waardoor ik mooie vooruitgang kon boeken.Bovendien kreeg ik toegang tot de frontendcode in GitLab, wat betekende dat ik ook daar binnenkort kon starten.",
            "Donderdag stond in het teken van verdieping.Ik heb bewust tijd genomen om EF Core beter te begrijpen: hoe dbContext werkt, hoe relaties werken en wat er precies gebeurt bij database - interacties.Door niet enkel te focussen op \"het werkend krijgen\", maar ook op het begrijpen van de achterliggende werking, voel ik dat mijn kennis sterker wordt.",
            "Vrijdag ben ik gestart met de frontend in Angular en heb ik gewerkt aan de inschrijvingenpagina.Het grootste deel daarvan is ondertussen afgewerkt.Er blijven nog twee functies over die ik volgende week zal implementeren, maar de basis staat er en alles begint mooi samen te komen.",
            "Terugkijkend was dit een week waarin ik niet alleen technische vooruitgang heb geboekt, maar ook heb geleerd hoe belangrijk nauwkeurigheid, samenwerking en dieper begrip zijn binnen development.Kleine fouten kunnen veel tijd kosten, maar leveren uiteindelijk ook waardevolle inzichten op.Op naar volgende week, waar ik de laatste functionaliteiten verder zal uitwerken en alles verder zal verfijnen."
        ]
    ],
    [
        [
            "Deze week stond in het teken van structuur opzetten, efficiënter leren werken en omgaan met de minder zichtbare — maar minstens even belangrijke — kant van development.",
            "Maandag kreeg ik toegang tot het Jira - board, wat meteen zorgde voor meer overzicht in de taken en planning.Daarnaast hebben we een database opgezet in een Docker - container.We leerden ook hoe we binnen dit project een nieuwe pagina aan het navigatiemenu moeten toevoegen, wat handig is voor extra pagina's aan te maken.Een belangrijke ontdekking was dat ik met PrimeNG veel minder TypeScript - code hoef te schrijven.Als ik dat eerder had beseft, had me dat al heel wat tijd kunnen besparen.",
            "Dinsdag heb ik mijn eerdere TypeScript - functionaliteiten grotendeels vervangen door PrimeNG - oplossingen.Dat zorgde niet alleen voor kortere code, maar ook voor een nettere en efficiëntere implementatie.Vervolgens heb ik alle nodige data in de database geplaatst zodat alles correct getest kon worden.Daarna ben ik begonnen met het mobiel maken van de enrollments - pagina.Dat was een taak die meer aandacht vroeg dan verwacht.",
            "Woensdag heb ik eerst het design van de knoppen op de enrollments - pagina aangepast.Daarna heb ik de volledige pagina responsive gemaakt.Dat proces nam behoorlijk wat tijd in beslag, vooral omdat elk detail correct moest schalen en werken op verschillende schermgroottes.In de namiddag hadden we een vergadering, waarna ik gestart ben met de flows - pagina.De eerste sectie daarvan heb ik meteen afgewerkt én responsive gemaakt.",
            "Donderdag werkte ik 's ochtends de CSS van de flows - pagina verder af.Daarna begon ik aan de TypeScript - en PrimeNG - functionaliteiten.Tegen de namiddag had ik alles geïmplementeerd, al liep ik even vast op een specifieke functionaliteit omdat ik de vereisten verkeerd had begrepen.Na wat herbekijken en aanpassen is het uiteindelijk toch gelukt.Vervolgens probeerde ik mijn branch te rebasen om een merge request aan te maken, maar ik kreeg te maken met stevige merge - conflicten.Dat zorgde voor een onverwachte uitdaging.",
            "Vrijdag stond grotendeels in het teken van het oplossen van die rebase - problemen.Het kostte behoorlijk wat tijd om alles correct samen te voegen zodat ik mijn merge request kon voorbereiden.Daarnaast heb ik scripts gerund en de connection string aangepast om de API correct werkend te krijgen.Tot slot heb ik nog extra informatie opgezocht over EF Core om mijn begrip verder te verdiepen."
        ]
    ],
    [
        [
            "Deze week heb ik voornamelijk gewerkt aan de inschrijvingspagina. Ik heb de frontend volledig herwerkt omdat de vorige versie fouten bevatte. Alle onderdelen van de frontend werden opnieuw geïmplementeerd, inclusief de datagrids, en ik heb ervoor gezorgd dat de verschillende pagina's correct responsive zijn zodat ze op verschillende schermformaten goed functioneren.",
            "Daarnaast heb ik het onderdeel voor massa-inschrijvingen toegevoegd aan de inschrijvingspagina. Dit vereiste een goede afstemming met de bestaande structuur van de applicatie. Ook heb ik extra functionaliteiten toegevoegd aan de frontend om de gebruiksvriendelijkheid en volledigheid van de pagina te verbeteren.",
            "Een belangrijk deel van mijn tijd ging naar het beter begrijpen van de backend en de databank. Door zowel in de voormiddag als namiddag hier intensief mee bezig te zijn, heb ik meer inzicht gekregen in hoe de gegevens worden verwerkt en hoe de verschillende onderdelen van het project met elkaar verbonden zijn. Dit helpt mij om gerichter en efficiënter verder te werken aan nieuwe functionaliteiten.",
            "Tot slot heb ik bijkomende documentatie doorgenomen om mijn kennis van het project te verdiepen. Naast het technische werk heb ik ook verder gewerkt aan mijn blog, zodat mijn voortgang en leerproces goed worden bijgehouden."
        ]
    ],
    [
        [
            "Deze week heb ik verder gewerkt aan de ontwikkeling van het inschrijvingssysteem. Het was een week waarin ik mij vooral heb verdiept in backendontwikkeling en het schrijven van queries, wat voor mij nog relatief nieuw is. Hierdoor duurden sommige taken iets langer dan verwacht, maar ik heb wel veel kunnen bijleren.",
            "Op maandag ben ik begonnen met het schrijven van een deel van de backend voor de inschrijvingen. Omdat ik nog niet volledig gewend ben aan backendontwikkeling, moest ik hier wat meer tijd voor nemen. In de namiddag hadden we een meeting via Microsoft Teams waarin we onze vooruitgang konden tonen. Tijdens deze meeting kregen we ook feedback, die we later konden verwerken in ons werk.",
            "Dinsdag ben ik gestart met het verwerken van deze feedback in de frontend. Dit gaf me de kans om de opmerkingen uit de meeting meteen om te zetten in verbeteringen binnen de applicatie.",
            "Woensdag heb ik mij vooral gefocust op het leren schrijven van LINQ-queries. Hiervoor moest ik eerst wat leerstof opnieuw bekijken, maar na wat oefenen begon het beter te lukken. Uiteindelijk heb ik de eerste vijf queries voor het inschrijvingssysteem kunnen schrijven.",
            "Donderdag heb ik in de voormiddag verder gewerkt aan deze queries. In de namiddag had ik een gesprek met mijn stagebegeleider en andere studenten om te bespreken hoe onze stage verloopt. Later op de dag had ik ook nog een vergadering met Kevin om verder af te stemmen over het project.",
            "Op vrijdag heb ik nog enkele onderdelen van de backend binnengehaald (gepulled). Daarbij merkte ik dat ik een fout had gemaakt door database\u00adlogica rechtstreeks in de controllers te schrijven. Dit was een leermoment voor mij, omdat ik nu beter begrijp dat deze logica eigenlijk in een andere laag van de applicatie hoort.",
            "Over het algemeen was het een leerzame week waarin ik mijn kennis van backendontwikkeling en LINQ verder heb kunnen uitbreiden. Hoewel ik soms wat moest zoeken naar de juiste aanpak, merk ik dat het stilaan vlotter begint te gaan."
        ]
    ],
    [
        [
            "Deze week heb ik verder gewerkt aan het inschrijvingssysteem en zowel aan de backend als de frontend verbeteringen aangebracht. Daarnaast kwam ik ook enkele technische problemen tegen die uiteindelijk goede leermomenten bleken te zijn.",
            "Op maandag had ik problemen met de gebruiker van mijn databank. Hierdoor kon de user geen commands uitvoeren op de databank. Ik heb bijna de hele dag geprobeerd om dit probleem op te lossen. Uiteindelijk heb ik samen met Achraf en Rabin het probleem kunnen vinden en oplossen, waardoor de databankgebruiker weer correct kon werken.",
            "Dinsdag heb ik mij beziggehouden met het omzetten van SQL-queries naar LINQ-queries. Dit was een goede oefening om mijn kennis van LINQ verder te verbeteren en om de backend beter te laten aansluiten op de technologieën die we gebruiken in het project.",
            "Woensdag heb ik verder gewerkt aan de frontend. Daarnaast heb ik ook enkele SQL-queries die fouten gaven nagekeken en gecorrigeerd, zodat ze correct uitgevoerd konden worden.",
            "Op donderdag heb ik opnieuw verder gewerkt aan de frontend van de applicatie. Later op de dag had ik ook een gesprek met mijn stagebegeleider over hoe de stage verloopt. Daarnaast had ik nog een vergadering met het team om de voortgang van het project te bespreken.",
            "Op vrijdag heb ik een bestand dat John had doorgestuurd ingesteld. Daarna ben ik begonnen met het verwerken van feedback die we hadden gekregen over de frontend, zodat de applicatie verder verbeterd kon worden.",
            "Deze week stond dus vooral in het teken van het oplossen van technische problemen, het verbeteren van queries en het verder ontwikkelen van de frontend. Door samen te werken met collega's en feedback te verwerken, heb ik opnieuw veel kunnen bijleren."
        ]
    ],
    [
        [
            "Deze week stond in het teken van het afronden van de frontend van inschrijvingen en het zetten van mijn eerste stappen in de backend. Het was een leerrijke week waarin ik zowel technische uitdagingen tegenkwam als vooruitgang boekte in mijn ontwikkeling als developer.\n\nAan het begin van de week heb ik feedback op de frontend verwerkt.Hierbij zat een probleem waar ik al een tijdje mee worstelde, maar dat ik uiteindelijk heb kunnen oplossen.Dit gaf me een goed gevoel en meer vertrouwen in mijn probleemoplossend vermogen.",
            "Een groot deel van de week heb ik besteed aan het schrijven en verbeteren van LINQ queries. Dit verliep niet altijd zonder problemen.Zo kreeg ik te maken met een issue in Docker waardoor de database tijdelijk niet werkte.Dit zorgde voor wat frustratie, maar uiteindelijk heb ik het probleem kunnen oplossen.\n\nOp het einde van de week heb ik gewerkt aan inschrijvingsqueries. Hierbij kwam ik nog enkele moeilijkheden tegen, waardoor het langer duurde dan verwacht, maar ik heb wel afgekregen.\n\nDeze week voelde als een duidelijke stap vooruit in mijn stage.Ik heb niet alleen mijn frontend werk afgerond, maar ook de eerste stappen gezet in backend development en het werken met databases.Hoewel ik op enkele momenten vastliep, merk ik dat ik steeds sneller oplossingen begin te vinden."
        ]
    ]
]